### ISSUE TITLE
[Bug]: Importing note with colored text 

### ISSUE THREAD

**Issue by olkido** [vzhd1701/enex2notion#1]
### enex2notion version

0.1.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

Monterey - 12.0.1

### Bug description

I am getting attached error when trying to import a note (text only, but with an enumerated list and colored text in it). 
PS: many thanks for this tool! :) 

### Log excerpt

```shell
Traceback (most recent call last):
  File "/Users/olkido/Library/Python/3.8/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 100, in main
    cli(sys.argv[1:])
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 95, in cli
    enex_uploader.upload(enex_input)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 54, in upload
    note_blocks = parse_note(note, self.add_meta)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser.py", line 19, in parse_note
    note_blocks = parse_note_dom(note_dom)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_dom.py", line 38, in parse_note_dom
    block = _parse_block(child)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_dom.py", line 77, in _parse_block
    return tag_parser(element)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_elements.py", line 36, in parse_list
    nodes[-1].children.extend(parse_list(subelement))
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_elements.py", line 31, in parse_list
    li_item = _parse_list_item(subelement, is_ul)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_elements.py", line 45, in _parse_list_item
    li_text = extract_string(list_item)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/string_extractor.py", line 18, in extract_string
    string_blocks = _extract_blocks(div_lines)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/string_extractor.py", line 39, in _extract_blocks
    string_properties = resolve_string_properties(parent_stack)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/string_extractor_properties.py", line 23, in resolve_string_properties
    tag_property = tag_map[tag.name](tag)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/string_extractor_properties.py", line 41, in _resolve_span
    color = extract_color(style)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/colors.py", line 87, in extract_color
    color = color_extract_func(match.group(1))
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/colors.py", line 116, in _extract_foreground_rgb
    rbg_fg = _parse_rgb(rgb_str)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/colors.py", line 134, in _parse_rgb
    color_str = re.match("^#(.*?)$", color).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by vzhd1701** [comment]
Could you please share the original note? Or copy the fragment with colored text into another note and share it?

**Comment by olkido** [comment]
https://www.evernote.com/shard/s49/sh/b4415148-44e1-db5e-7358-59bb4ebfdd3c/

best,
—
olga

**Comment by vzhd1701** [comment]
I am sorry, but this fragment does not seem to have any color. Could you please share the one with color? You can copy the note, remove everything else and change the text, but keep the original formatting with color.

**Comment by olkido** [comment]
Hm, somehow the link above was not the right shareable link. Maybe try this one? I see it as having color on an incognito browser window. 
https://www.evernote.com/shard/s49/sh/b4415148-44e1-db5e-7358-59bb4ebfdd3c/6295144d1650211bc58046b0744237ed

**Comment by vzhd1701** [comment]
Fixed, please check the new version!
