### ISSUE TITLE
[Bug]: Problem downloading https://sourceforge.mirrorservice.org/l/li/libpng/libpng16/1.6.4

### ISSUE THREAD

**Issue by rusalki** [vzhd1701/enex2notion#104]
### enex2notion version

Installation issue

### What OS are you using?

MacOS

### OS Version / Linux distribution

Mac OS 10.11.6

### Bug description

Hi, noob here trying to get my Evernote notes into Notion. Managed to do all the steps except the "brew install enex2notion" step which threw up this error:
Trying a mirror...
==> Downloading https://sourceforge.mirrorservice.org/l/li/libpng/libpng16/1.6.4
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.

curl: (6) Could not resolve host: sourceforge.mirrorservice.org
Error: enex2notion: Failed to download resource "libpng"
Download failed: https://sourceforge.mirrorservice.org/l/li/libpng/libpng16/1.6.40/libpng-1.6.40.tar.xz

Did I do something wrong? Would love to know how to get this installed! (Please explain simply, sorry! I'm amazed I got this far following the instructions to be honest!) Thank you!

**Comment by vzhd1701** [comment]
You did nothing wrong, the problem is on the `homebrew` side here. Was there anything else in the log before `Trying a mirror...`? It may be just a temporary hiccup.

**Comment by rusalki** [comment]
Hi! Thanks for responding! Here's the bit before that:

```
==> Fetching dependencies for enex2notion: libpng, freetype, gumbo-parser, mpdecimal, ca-certificates, openssl@3, readline, sqlite, xz, libffi, python@3.11, fontconfig, pcre2, gettext, ninja, python@3.12, meson, python-setuptools, glib, util-macros, xorgproto, libxau, libxdmcp, xcb-proto, libxcb, xtrans, libx11, libxext, libxrender, lzo, pixman, cairo, cmake, graphite2, icu4c, bison, gobject-introspection, harfbuzz, m4, autoconf, automake, libtool, jbig2dec, nasm, jpeg-turbo, mujs, lz4, zstd, libtiff, little-cms2, berkeley-db, gdbm, perl, help2man, flex, doxygen, openjpeg, mupdf, swig, pymupdf, python@3.10, python-certifi, libxml2, python-lxml and six
==> Fetching libpng
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/6b973ed
######################################################################### 100.0%
==> Downloading https://downloads.sourceforge.net/project/libpng/libpng16/1.6.40

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Trying a mirror...
==> Downloading https://sourceforge.mirrorservice.org/l/li/libpng/libpng16/1.6.4
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.

curl: (6) Could not resolve host: sourceforge.mirrorservice.org
Error: enex2notion: Failed to download resource "libpng"
Download failed: https://sourceforge.mirrorservice.org/l/li/libpng/libpng16/1.6.40/libpng-1.6.40.tar.xz
```
I just tried installing it again, and got the same error sadly!

**Comment by vzhd1701** [comment]
I think you are getting SSL errors because your [OS version is very old](https://endoflife.date/macos) and you are not receiving SSL updates anymore. You can try running this before brew install command to avoid SSL checks altogether:
```bash
echo "--insecure" > ~/.curlrc
export HOMEBREW_CURLRC=1
```

**Comment by rusalki** [comment]
Thank you!! Yes I just discovered last night that my OS is... ancient! I tried what you suggested and managed to get a lot further! Yay! THANK YOU! Then I encountered this:

```
==> Fetching libpng
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/bd53e4a
######################################################################### 100.0%
==> Downloading https://downloads.sourceforge.net/project/libpng/libpng16/1.6.40
==> Downloading from https://kumisystems.dl.sourceforge.net/project/libpng/libpn
######################################################################### 100.0%
==> Fetching freetype
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/bd53e4a
######################################################################### 100.0%
==> Downloading https://downloads.sourceforge.net/project/freetype/freetype2/2.1
==> Downloading from https://netcologne.dl.sourceforge.net/project/freetype/free
######################################################################### 100.0%
==> Fetching gumbo-parser
==> Downloading https://ghcr.io/v2/homebrew/core/gumbo-parser/manifests/0.10.1
######################################################################### 100.0%
Error: undefined method `index_by' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1218:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1237:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:704:in `fetch_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1197:in `block in fetch_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1197:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1197:in `fetch_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1230:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:277:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:247:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:247:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:295:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
MacBook-Air:~ Macbook$ cd ~/Documents/evernote
MacBook-Air:evernote Macbook$ enex2notion --token longasstokentextthatIhaveshortenedforthispost notes.enex
-bash: enex2notion: command not found
```

Maybe I didn't follow the instructions correctly? In the meantime, I'll go shop on Amazon for a new laptop!!

**Comment by vzhd1701** [comment]
You got another error during the installation. Homebrew usually supports only the three most recent versions of macOS, so you're out of luck here. I think you should try using the [pre-compiled binary](https://github.com/vzhd1701/enex2notion/releases/download/v0.3.1/bin_enex2notion_0.3.1_macos_x64.zip) instead of installing it via homebrew.

**Comment by rusalki** [comment]
Thank you! I really appreciate your help here. I will give that ago and if that doesn't work, I'll either get a new laptop (which I should anyway) or just pay for Evernote premium until I do! Thank you again!!
