### ISSUE TITLE
[Bug]: SSLError

### ISSUE THREAD

**Issue by devzhuchuanbo** [vzhd1701/enex2notion#106]
### enex2notion version

SSLError

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows11 Professional 23H2

### Bug description

I tried may times and it always ends with the SSLError.

### Log excerpt

```shell
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/loadUserContent (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 26, in cli
  File "enex2notion\cli_notion.py", line 21, in get_root
  File "enex2notion\cli_notion.py", line 31, in get_notion_client
  File "notion\client.py", line 113, in __init__
  File "notion\client.py", line 144, in _update_user_info
  File "ratelimit\decorators.py", line 113, in wrapper
  File "ratelimit\decorators.py", line 80, in wrapper
  File "notion\client.py", line 275, in post
  File "notion\client.py", line 283, in _post
  File "requests\sessions.py", line 637, in post
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/loadUserContent (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
[35912] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by devzhuchuanbo** [comment]
Problem solved! 

It was **Clash** that caused the error. Close it and try again; it will work. 

Write this commit for those who might have the same problem.
