### ISSUE TITLE
Started getting "413 Client Error: Payload Too Large" every time

### ISSUE THREAD

**Issue by chirul0** [vzhd1701/enex2notion#110]
### Discussed in https://github.com/vzhd1701/enex2notion/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **n0stress4me** December 24, 2022</sup>
I've been migrating from Evernote to Notion and this tool has been absolutely amazing.  It was working perfectly to import several thousand records across several ENEX files.  For some reason, it's stopped working now.  I'm not sure if I've reached some sort of limit with Notion API usage or if something else is going on.  I've tried running the script from different IP addresses, changing to Cloudfare DNS, using a VPN, and still the same issue.  I've also tried with different ENEX files of different sizes and same things.  Every time I run the script, the first record gets imported successfully and the second record errors out with the following:

Traceback (most recent call last):
  File "/opt/homebrew/bin/enex2notion", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli.py", line 47, in main
    cli(sys.argv[1:])
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli.py", line 32, in cli
    _process_input(enex_uploader, args.enex_input)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli.py", line 42, in _process_input
    enex_uploader.upload_notebook(path)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli_upload.py", line 56, in upload_notebook
    self.upload_note(note, note_idx)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli_upload.py", line 79, in upload_note
    _upload_note(self.notebook_root, note, note_blocks)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli_upload.py", line 103, in _upload_note
    upload_note(notebook_root, note, note_blocks)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/enex_uploader.py", line 20, in upload_note
    new_page = _make_page(note, root)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/enex_uploader.py", line 59, in _make_page
    root.collection.add_row(
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/collection.py", line 202, in add_row
    return self.add_row_block(columns=columns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/collection.py", line 219, in add_row_block
    with self._client.as_atomic_transaction():
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 469, in __exit__
    self.client.submit_transaction(operations)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 323, in submit_transaction
    self.post("submitTransaction", data)
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 298, in _post
    response.raise_for_status()
  File "/opt/homebrew/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: https://www.notion.so/api/v3/submitTransaction

So I can keep re-running it and each time the next one record gets imported successfully...and I guess eventually the 1471 records left to import will be completed, but I'd like to figure out why it's failing all of a sudden.
</div>

I've started hitting this issue.

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/enex_uploader.py", line 20, in upload_note
    _upload_note(root, note, note_blocks, keep_failed)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/enex_uploader.py", line 35, in _upload_note
    upload_block(new_page, block)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/enex_uploader_block.py", line 14, in upload_block
    new_block.set(p_key, p_value)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/notion/records.py", line 115, in set
    self._client.submit_transaction(
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/notion/client.py", line 323, in submit_transaction
    self.post("submitTransaction", data)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/notion/client.py", line 298, in _post
    response.raise_for_status()
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: https://www.notion.so/api/v3/submitTransaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/enex2notion", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli.py", line 47, in main
    cli(sys.argv[1:])
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli.py", line 32, in cli
    _process_input(enex_uploader, args.enex_input)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli.py", line 40, in _process_input
    enex_uploader.upload_notebook(enex_file)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli_upload.py", line 66, in upload_notebook
    self.upload_note(note, note_idx)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli_upload.py", line 90, in upload_note
    self._upload_note(self.notebook_root, note, note_blocks)
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli_upload.py", line 118, in _upload_note
    self._attempt_upload(
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/cli_upload.py", line 130, in _attempt_upload
    return upload_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/enex2notion/0.3.1_3/libexec/lib/python3.12/site-packages/enex2notion/enex_uploader.py", line 22, in upload_note
    raise NoteUploadFailException from e
enex2notion.utils_exceptions.NoteUploadFailException
```

**Comment by chirul0** [comment]
It seems to be getting stuck on one particular note (not large at all), which I've exported individually and deleted from EN. I resynced the backup, exported and am trying again w/o that 1 note.

**Comment by chirul0** [comment]
Something about that one note was causing this error. After I removed it and resynced it was able to continue but then started hitting the issue in https://github.com/vzhd1701/enex2notion/issues/111
