### ISSUE TITLE
[Bug]: [11712] Failed to execute script '__main__' due to unhandled exception! (enex2notion.utils_exceptions.NoteUploadFailException)

### ISSUE THREAD

**Issue by simonebaracchi** [vzhd1701/enex2notion#121]
### enex2notion version

0.3.1

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 Pro

### Bug description

After uploading several notes, the process interrupts with this stack trace:

`INFO: Uploading note 4 out of 17 'Camera da letto'
WARNING: Failed to upload note 'Camera da letto' to Notion! Retrying...
WARNING: Failed to upload note 'Camera da letto' to Notion! Retrying...
WARNING: Failed to upload note 'Camera da letto' to Notion! Retrying...
WARNING: Failed to upload note 'Camera da letto' to Notion! Retrying...
ERROR: Failed to upload note 'Camera da letto' to Notion!
Traceback (most recent call last):
  File "enex2notion\enex_uploader.py", line 20, in upload_note
  File "enex2notion\enex_uploader.py", line 35, in _upload_note
  File "enex2notion\enex_uploader_block.py", line 17, in upload_block
  File "enex2notion\enex_uploader_block.py", line 51, in _upload_file
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://prod-files-secure.s3.us-west-2.amazonaws.com/(very very long url omitted for readability)&x-id=PutObject

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 32, in cli
  File "enex2notion\cli.py", line 40, in _process_input
  File "enex2notion\cli_upload.py", line 66, in upload_notebook
  File "enex2notion\cli_upload.py", line 90, in upload_note
  File "enex2notion\cli_upload.py", line 118, in _upload_note
  File "enex2notion\cli_upload.py", line 130, in _attempt_upload
  File "enex2notion\enex_uploader.py", line 22, in upload_note
enex2notion.utils_exceptions.NoteUploadFailException
[11712] Failed to execute script '__main__' due to unhandled exception!
`

It may be interesting to point out that the failing note contains a somewhat large amount of images (about 35) adding up to some megabytes.

### Log excerpt

```shell
Not much more info:

`DEBUG: Creating new page for note 'Camera da letto'
DEBUG: Upload error:
Traceback (most recent call last):
  File "enex2notion\enex_uploader.py", line 20, in upload_note
  File "enex2notion\enex_uploader.py", line 35, in _upload_note
  File "enex2notion\enex_uploader_block.py", line 17, in upload_block
  File "enex2notion\enex_uploader_block.py", line 51, in _upload_file
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://prod-files-secure.s3.us-west-2.amazonaws.com/(very very long url)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "enex2notion\cli_upload.py", line 130, in _attempt_upload
  File "enex2notion\enex_uploader.py", line 22, in upload_note
enex2notion.utils_exceptions.NoteUploadFailException
WARNING: Failed to upload note 'Camera da letto' to Notion! Retrying...`
```

**Comment by ChetanArvindPatil** [comment]
@vzhd1701 

Same error

> ERROR: Failed to upload note 'Social' to Notion!                                
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader.py", line 20, in upload_note
>     _upload_note(root, note, note_blocks, keep_failed)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader.py", line 35, in _upload_note
>     upload_block(new_page, block)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader_block.py", line 17, in upload_block
>     _upload_file(new_block, block.resource)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader_block.py", line 55, in _upload_file
>     new_block.file_id = _extract_file_id(upload_data["url"])
>                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader_block.py", line 69, in _extract_file_id
>     raise ValueError(f"Uploaded file URL format changed: {url}")
> ValueError: Uploaded file URL format changed: attachment:dee03ff4-edb0-44e6-97c9-72177f68dcce:1f642.svg
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/homebrew/bin/enex2notion", line 8, in <module>
>     sys.exit(main())
>              ~~~~^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli.py", line 47, in main
>     cli(sys.argv[1:])
>     ~~~^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli.py", line 32, in cli
>     _process_input(enex_uploader, args.enex_input)
>     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli.py", line 40, in _process_input
>     enex_uploader.upload_notebook(enex_file)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli_upload.py", line 66, in upload_notebook
>     self.upload_note(note, note_idx)
>     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli_upload.py", line 90, in upload_note
>     self._upload_note(self.notebook_root, note, note_blocks)
>     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli_upload.py", line 118, in _upload_note
>     self._attempt_upload(
>     ~~~~~~~~~~~~~~~~~~~~^
>         upload_note,
>         ^^^^^^^^^^^^
>     ...<4 lines>...
>         self.rules.keep_failed,
>         ^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/cli_upload.py", line 130, in _attempt_upload
>     return upload_func(*args, **kwargs)
>   File "/opt/homebrew/Cellar/enex2notion/0.3.1_11/libexec/lib/python3.13/site-packages/enex2notion/enex_uploader.py", line 22, in upload_note
>     raise NoteUploadFailException from e
> enex2notion.utils_exceptions.NoteUploadFailException
