### ISSUE TITLE
[Bug]: Importing web-clipped note

### ISSUE THREAD

**Issue by olkido** [vzhd1701/enex2notion#2]
### enex2notion version

0.1.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

Monterey - 12.0.1

### Bug description

I am getting attached error when trying to import a note (web clipped by Evernote -- this is the note link https://www.evernote.com/shard/s49/sh/af12db2f-4832-49c9-b02f-07fd7f9c9bff/835547ad37efc6b14325ac0eaace5876
 )

In general it would be very nice if the tool could proceed to the next note if it encounters an error while parsing a note (as opposed to stopping the importing process entirely:) ) if at all possible.

### Log excerpt

```shell
DEBUG: Parsing note '(21) Torque and angular momentum | AP®︎ Physics 1 | Science | Khan Academy'...
DEBUG: Skipping webclip block
Traceback (most recent call last):
  File "/Users/olkido/Library/Python/3.8/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 100, in main
    cli(sys.argv[1:])
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 95, in cli
    enex_uploader.upload(enex_input)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/cli.py", line 54, in upload
    note_blocks = parse_note(note, self.add_meta)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser.py", line 19, in parse_note
    note_blocks = parse_note_dom(note_dom)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_dom.py", line 38, in parse_note_dom
    block = _parse_block(child)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_dom.py", line 77, in _parse_block
    return tag_parser(element)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_e_media.py", line 53, in parse_img
    img_resource = _parse_img_resource(src)
  File "/Users/olkido/Library/Python/3.8/lib/python/site-packages/enex2notion/note_parser_e_media.py", line 64, in _parse_img_resource
    imd_bin = base64.b64decode(bin_src.split("base64,")[1])
IndexError: list index out of range
```

**Comment by vzhd1701** [comment]
Unfortunately, my program does not support webclips. Those are pure HTML, while my program's primary use case is to convert Evernote's simplified pseudo-html into Notion format. So you will have better luck converting WebClips into `*.md` format and then upload them using [md2notion](https://github.com/Cobertos/md2notion).

Anyway you shouldn't encounter this error now. Please check out the new version.
