### ISSUE TITLE
[Bug]: KeyError: 'block'

### ISSUE THREAD

**Issue by tomdwo** [vzhd1701/enex2notion#24]
### enex2notion version

0.2.5

### What OS are you using?

Windows

### OS Version / Linux distribution

Ubuntu 20.04.4 

### Bug description

I cannot import any .enex files with enex2notion, although the files can be parsed in dry run.

Seems that the script is able to connect/authenticate with notion with the provided tokens. When providing an invalid token I get an authentication error ( `401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent`).  

Also tried in Windows and even did export with evernote-backup, always the same result.

File with one note (test.enex) is attached.
[test.zip](https://github.com/vzhd1701/enex2notion/files/8356375/test.zip)
 

### Log excerpt

```shell
enex2notion --verbose "test.enex"
WARNING: No token provided, dry run mode. Nothing will be uploaded to Notion!
INFO: Processing notebook 'test'...

--------
enex2notion --verbose --token eaaeb5...96ba11d8c904d "test.enex"
Traceback (most recent call last):
  File "/home/tom/.local/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.local/lib/python3.8/site-packages/enex2notion/cli.py", line 152, in main
    cli(sys.argv[1:])
  File "/home/tom/.local/lib/python3.8/site-packages/enex2notion/cli.py", line 123, in cli
    root = get_import_root(
  File "/home/tom/.local/lib/python3.8/site-packages/enex2notion/enex_uploader.py", line 19, in get_import_root
    for page in client.get_top_level_pages():
  File "/home/tom/.local/lib/python3.8/site-packages/notion/client.py", line 159, in get_top_level_pages
    return [self.get_block(bid) for bid in records["block"].keys()]
KeyError: 'block'
```

**Comment by emphaticsunshine** [comment]
Seeing the same problem:

```
Traceback (most recent call last):
  File "/usr/local/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/enex2notion/cli.py", line 152, in main
    cli(sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/enex2notion/cli.py", line 123, in cli
    root = get_import_root(
  File "/usr/local/lib/python3.8/site-packages/enex2notion/enex_uploader.py", line 19, in get_import_root
    for page in client.get_top_level_pages():
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 159, in get_top_level_pages
    return [self.get_block(bid) for bid in records["block"].keys()]
KeyError: 'block'
```

**Comment by dzimitori** [comment]
The same problem (Windows 10):
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent
[18636] Failed to execute script '__main__' due to unhandled exception!

**Comment by vzhd1701** [comment]
This glitch occurred only for empty accounts. FIxed now. (https://github.com/vzhd1701/enex2notion/commit/807b04caa464abfef3e6745870c4f48682c5a658)
@dzimitori It seems like your token is invalid.

**Comment by tomdwo** [comment]
Thank you @vzhd1701, works perfectly now :-)

**Comment by dzimitori** [comment]
@vzhd1701 Thank you! My fault, now it worked!
