### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by patrickplaggenborg** [vzhd1701/enex2notion#3]
### enex2notion version

0.1.1

### What OS are you using?

MacOS

### OS Version / Linux distribution

12.0.1

### Bug description

Importing an ENEX file with 800+ notes.

Worked fine for the first 40 notes or so. Then gave this error.

What happened? How can I help debug this?

### Log excerpt

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 100, in main
    cli(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 95, in cli
    enex_uploader.upload(enex_input)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 54, in upload
    note_blocks = parse_note(note, self.add_meta)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser.py", line 19, in parse_note
    note_blocks = parse_note_dom(note_dom)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_dom.py", line 38, in parse_note_dom
    block = _parse_block(child)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_dom.py", line 77, in _parse_block
    return tag_parser(element)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_e_div.py", line 34, in parse_div
    return parse_text(element)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_e_div.py", line 42, in parse_text
    return NotionTextBlock(text_prop=extract_string(element))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor.py", line 18, in extract_string
    string_blocks = _extract_blocks(div_lines)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor.py", line 39, in _extract_blocks
    string_properties = resolve_string_properties(parent_stack)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor_properties.py", line 23, in resolve_string_properties
    tag_property = tag_map[tag.name](tag)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor_properties.py", line 41, in _resolve_span
    color = extract_color(style)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 89, in extract_color
    color = color_extract_func(match.group(1))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 118, in _extract_foreground_rgb
    rbg_fg = _parse_rgb(rgb_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 133, in _parse_rgb
    color_str = re.match(r"^rgb\((.*?)\)$", color).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by vzhd1701** [comment]
Could you run it with `--verbose` flag to see which note is causing the crash and and then share a copy of that note? As I can tell by the log you provided the crash is caused by some colored text. If you can't share the whole note, maybe you could extract fragments of colored text from it in a separate note and share that.
```shell
$ enex2notion --verbose your_enex_file.enex
```

**Comment by patrickplaggenborg** [comment]
I created this ENEX file with just the note causing the problem:
[20211205 debug 1.enex.zip](https://github.com/vzhd1701/enex2notion/files/7655591/20211205.debug.1.enex.zip)

```python Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 100, in main
    cli(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 95, in cli
    enex_uploader.upload(enex_input)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 54, in upload
    note_blocks = parse_note(note, self.add_meta)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser.py", line 19, in parse_note
    note_blocks = parse_note_dom(note_dom)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_dom.py", line 38, in parse_note_dom
    block = _parse_block(child)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_dom.py", line 77, in _parse_block
    return tag_parser(element)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_e_div.py", line 34, in parse_div
    return parse_text(element)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/note_parser_e_div.py", line 42, in parse_text
    return NotionTextBlock(text_prop=extract_string(element))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor.py", line 18, in extract_string
    string_blocks = _extract_blocks(div_lines)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor.py", line 39, in _extract_blocks
    string_properties = resolve_string_properties(parent_stack)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor_properties.py", line 23, in resolve_string_properties
    tag_property = tag_map[tag.name](tag)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/string_extractor_properties.py", line 41, in _resolve_span
    color = extract_color(style)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 89, in extract_color
    color = color_extract_func(match.group(1))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 118, in _extract_foreground_rgb
    rbg_fg = _parse_rgb(rgb_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/colors.py", line 133, in _parse_rgb
    color_str = re.match(r"^rgb\((.*?)\)$", color).group(1)
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by vzhd1701** [comment]
It should be fixed now, please check out the new version!

**Comment by patrickplaggenborg** [comment]
Thanks, that worked!
