### ISSUE TITLE
[Bug]: enex_parser_xml exception

### ISSUE THREAD

**Issue by torx25** [vzhd1701/enex2notion#34]
### enex2notion version

0.2.13

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 21H2 Home 19044.1706

### Bug description

While uploading a file (.enex) I get an error:

Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 32, in cli
  File "enex2notion\cli.py", line 42, in _process_input
  File "enex2notion\cli_upload.py", line 53, in upload_notebook
  File "enex2notion\enex_parser.py", line 23, in count_notes
  File "enex2notion\enex_parser_xml.py", line 23, in iter_process_xml_elements
  File "xml\etree\ElementTree.py", line 1227, in iterator
  File "xml\etree\ElementTree.py", line 1302, in read_events
  File "xml\etree\ElementTree.py", line 1274, in feed
xml.etree.ElementTree.ParseError: undefined entity &nbsp;: line 7144081, column 174
[16176] Failed to execute script '__main__' due to unhandled exception!

**Comment by vzhd1701** [comment]
Could you please share the enex file that caused this error?

**Comment by torx25** [comment]
[1.zip](https://github.com/vzhd1701/enex2notion/files/8781408/1.zip)
It happens to all my .enex files I'm trying to upload.

**Comment by vzhd1701** [comment]
Is it an exact same error every time?

**Comment by torx25** [comment]
Yes it is
![2022-05-26 22_28_02-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/52157013/170562874-dddcdc3d-545e-4fc7-9561-56b720be7e66.png)
.

**Comment by vzhd1701** [comment]
This error is different from the one you had with the first notebook.

There was a Notion server-side glitch. Please try again, "403 Client Error" crash should be resolved now.

**Comment by torx25** [comment]
Temporarily resolved by downgrading to v. 0.2.12.
