### ISSUE TITLE
[Bug]: 403 Client Error

### ISSUE THREAD

**Issue by alex0103-git** [vzhd1701/enex2notion#35]
### enex2notion version

enex2notion 0.2.12

### What OS are you using?

MacOS

### OS Version / Linux distribution

Monterey 12.3.1

### Bug description

While uploading a file (.enex) I get an error 403

### Log excerpt

```shell
Traceback (most recent call last):
  File "enex2notion/__main__.py", line 4, in <module>
  File "enex2notion/cli.py", line 175, in main
  File "enex2notion/cli.py", line 134, in cli
  File "enex2notion/cli.py", line 165, in get_root
  File "enex2notion/enex_uploader.py", line 26, in get_notion_client
  File "notion/client.py", line 96, in __init__
  File "notion/client.py", line 127, in _update_user_info
  File "notion/client.py", line 270, in post
  File "requests/models.py", line 960, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.notion.so/api/v3/loadUserContent
[3314] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by vzhd1701** [comment]
It was a Notion server-side hiccup, it should be resolved by now. Please try again.
