### ISSUE TITLE
Error 429: Too many Request for URL https://www.notion.so/api/v3/loadusercontent

### ISSUE THREAD

**Issue by rockon365** [vzhd1701/enex2notion#44]
Hey! Trying to use enex2notion today and received that error. This is the first time that has happened. Do you know if Notion has started limiting imports? My .enex wasn't any bigger than some I've previously transferred. Thank you!

**Comment by vzhd1701** [comment]
Did you run multiple uploads in parallel?

**Comment by rockon365** [comment]
Just the one.

**Comment by vzhd1701** [comment]
Strange. Maybe they just changed the limits. This should go away after a while, ~15 minutes or more. Please try again later and tell if it happens again.

**Comment by rockon365** [comment]
Hmm, happened again. I waited for about 3 hours. Stopped four notes into the transfer which is the same as the first time.

**Comment by vzhd1701** [comment]
How many blocks do those notes have?

**Comment by rockon365** [comment]
I'm not sure how to tell exactly, but just roughly counting between 30 and 100.

**Comment by rockon365** [comment]
I did come across this which you've probably already seen: https://developers.notion.com/reference/request-limits

It mentions requests at an average of 3 per second can cause that error. Is there a way I can throttle my uploads?

**Comment by vzhd1701** [comment]
Thank you, I haven't seen this one oddly enough. I will implement the fix to limit requests per second tomorrow. For now you'll have to use some kind of throttling proxy.

**Comment by rockon365** [comment]
No worries! I'll wait and try out the fix. Implementing a throttle proxy is a bit above my knowledge at the moment! :)

**Comment by vzhd1701** [comment]
I've made some changes that should prevent this error from happening again. Please check out the new version and tell how it works for you.

**Comment by rockon365** [comment]
Sorry for the delay. I just tried with 0.2.17 and had the same issue. I'm going to remove the Note it keeps failing on and see if it will progress. I can't see anything out of the ordinary with this note, though.

**Comment by vzhd1701** [comment]
What is your OS and how do you install enex2notion (pip, pipx, homebrew, standalone binary)? Could you also provide the log or exact traceback that you are getting with this error?

**Comment by rockon365** [comment]
Win10 using standalone binary. I tried without the note that kept tripping the error and did not have any issues. The note had a single line of text and 5 screenshots.

```
Traceback (most recent call last):
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\enex_uploader.py", line 37, in upload_note
    upload_block(new_page, block)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\note_uploader.py", line 16, in upload_block
    _upload_file(new_block, block.resource)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\note_uploader.py", line 42, in _upload_file
    new_block.display_source = upload_data["url"]
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\maps.py", line 50, in fset
    self.set(path, python_to_api(value, **kwargs))
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\records.py", line 115, in set
    self._client.submit_transaction(
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\client.py", line 
290, in submit_transaction
    self.post("submitTransaction", data)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\client.py", line 
265, in post
    response.raise_for_status()
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.notion.so/api/v3/submitTransaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code      
    exec(code, run_globals)
  File "C:\Users\bleei\AppData\Local\Programs\Python\Python38-32\Scripts\enex2notion.exe\__main__.py", line 7, in <module>
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\cli.py", line 152, in main
    cli(sys.argv[1:])
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\cli.py", line 147, in cli
    enex_uploader.upload(enex_input)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\cli.py", line 89, in upload
    _upload_note(notebook_root, note, note_blocks)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\cli.py", line 46, in _upload_note
    upload_note(notebook_root, note, note_blocks)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\enex2notion\enex_uploader.py", line 40, in upload_note
    new_page.remove()
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\collection.py", line 668, in remove
    self._client.submit_transaction(
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\client.py", line 
290, in submit_transaction
    self.post("submitTransaction", data)
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\notion\client.py", line 
265, in post
    response.raise_for_status()
  File "c:\users\bleei\appdata\local\programs\python\python38-32\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.notion.so/api/v3/submitTransaction

```

**Comment by vzhd1701** [comment]
Are you sure you are running the right exe? According to the paths in your log it seems like you are running enex2notion installed with pip into your local Python at "c:\users\bleei\appdata\local\programs\python\python38-32\". Standalone exe usually hail from "C:\Users\%USERNAME%\AppData\Local\Temp\_MEI*".

You can run `enex2notion --version` to see if you are running correct version.

**Comment by rockon365** [comment]
![image](https://user-images.githubusercontent.com/62921887/181792983-a5e5b187-fbca-4941-9096-67829aea24b6.png)

I copied the .exe over to a different folder after downloading and am running it from the path shown in the screenshot. I wasn't able to locate the _MEI* folder.

**Comment by vzhd1701** [comment]
Did you run it as `.\enex2notion.exe` or `enex2notion.exe` when you got error last time?

Run `pip uninstall enex2notion` to make sure there is no other conflicting enex2notion in the system. According to your log it was running using outdated dependency.

**Comment by rockon365** [comment]
Oh!!! That makes more sense now. I was running as `enex2notion.exe`. I think several months back I installed it using pip. I wasn't thinking about the fact that not providing the .\ was causing it to pull from the older version. 

I'm going to make sure I run some more as `.\enex2notion.exe` and report back, but so far it looks good!
