### ISSUE TITLE
[Bug]: ImportError when running

### ISSUE THREAD

**Issue by murs313** [vzhd1701/enex2notion#46]
### enex2notion version

0.2.17

### What OS are you using?

MacOS

### OS Version / Linux distribution

macOS BigSur(11.6.7), Intel

### Bug description

Hi @vzhd1701 !
Thanks for developing the amazing tool.

I have installed enex2notion with Homebrew, but when I run it, I get the following error.

I think this is not an issue with enex2notion, but I want some help, so I opened this issue.
If you can think of a solution, please tell me.

### Log excerpt

```shell
% enex2notion --verbose
Traceback (most recent call last):
  File "/usr/local/bin/enex2notion", line 5, in <module>
    from enex2notion.cli import main
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 9, in <module>
    from enex2notion.cli_upload import EnexUploader
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 9, in <module>
    from enex2notion.note_parser.note import parse_note
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/enex2notion/note_parser/note.py", line 12, in <module>
    from enex2notion.note_parser.note_type_based import parse_note_blocks_based_on_type
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/enex2notion/note_parser/note_type_based.py", line 8, in <module>
    from enex2notion.note_parser.webclip_pdf import parse_webclip_to_pdf
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/enex2notion/note_parser/webclip_pdf.py", line 6, in <module>
    import fitz
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/fitz/fitz.py", line 17, in <module>
    from . import _fitz
ImportError: dlopen(/usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/fitz/_fitz.cpython-310-darwin.so, 2): Symbol not found: _FT_Get_First_Char
  Referenced from: /usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/fitz/_fitz.cpython-310-darwin.so
  Expected in: /usr/local/opt/mupdf/lib/libmupdf.dylib
 in /usr/local/Cellar/enex2notion/0.2.17/libexec/lib/python3.10/site-packages/fitz/_fitz.cpython-310-darwin.so
```

**Comment by vzhd1701** [comment]
It's a Homebrew package issue. Will fix it now. Meanwhile you can use a [standalone binary](https://github.com/vzhd1701/enex2notion/releases/download/v0.2.17/bin_enex2notion_0.2.17_macos_x64.zip).

**Comment by vzhd1701** [comment]
Homebrew package should be fixed now. Please update and tell how it works for you.
```shell
brew update
brew upgrade vzhd1701/tap/csv2notion
```

**Comment by murs313** [comment]
@vzhd1701 , thanks for the fix!
I saw the fix here. https://github.com/vzhd1701/homebrew-tap/commit/ed01aff86fc4f2e8a6545d85d1296e03d668a838

It runs fine now!
```
% enex2notion --version
enex2notion 0.2.17
```

I'll try to use it :)
