### ISSUE TITLE
[Bug]: TypeError: %o format: an integer is required, not Bar

### ISSUE THREAD

**Issue by patrickplaggenborg** [vzhd1701/enex2notion#5]
### enex2notion version

0.1.2

### What OS are you using?

MacOS

### OS Version / Linux distribution

12.0.1

### Bug description

Got this error when importing a note.

Example ENEX file to debug:
[Debug.enex.zip](https://github.com/vzhd1701/enex2notion/files/7655878/Debug.enex.zip)

### Log excerpt

```shell
INFO: 'Evernote ENEX Import' page found
INFO: Processing notebook 'Debug'...
DEBUG: Parsing note 'xxxxxxxxxxxxxxxxxxxx'...
WARNING: Non-empty string element in root
INFO: Creating new page for note 'xxxxxxxxxxxxxxxxxxxx'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 100, in main
    cli(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 95, in cli
    enex_uploader.upload(enex_input)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/cli.py", line 59, in upload
    upload_note(notebook_root, note, note_blocks)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/enex2notion/enex_uploader.py", line 23, in upload_note
    for block in Bar(f"Uploading '{note.title}'").iter(note_blocks):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/progress/__init__.py", line 184, in iter
    with self:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/progress/__init__.py", line 136, in __enter__
    self.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/progress/__init__.py", line 171, in start
    self.update()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/progress/bar.py", line 38, in update
    message = self.message % self
TypeError: %o format: an integer is required, not Bar
```

**Comment by vzhd1701** [comment]
I am very sorry for so many glitches 😅

This one should be fixed now, please check out the new version.

**Comment by patrickplaggenborg** [comment]
No worries! I'm super happy you were able to create this tool with such dedication to make it work.

Happy to help debug this where needed because it fills a need for many people who are looking to switch from Evernote to Notion.

Thanks for the fix. I'll give the new version a try.

**Comment by patrickplaggenborg** [comment]
Worked, thank you!
