### ISSUE TITLE
[Bug]: .jar file cause all process failed

### ISSUE THREAD

**Issue by bxb100** [vzhd1701/enex2notion#50]
### enex2notion version

enex2notion 0.2.18

### What OS are you using?

MacOS

### OS Version / Linux distribution

MacOS 13 beta

### Bug description

Original note has jar file, but seems the notion don't allow upload, Can we ignore this mistake and continue the converting process?

### Log excerpt

```shell
WARNING: Failed to upload note 'xxxxxxxxxx' to Notion! Retrying...
 11%|████▌                                    | 2/18 [00:19<02:41, 10.12s/block]ERROR: Got 400 error attempting to POST to getUploadFileUrl, with data: {
  "bucket": "secure",
  "name": "commons-jexl-2.1.1.jar",
  "contentType": "application/octet-stream",
  "record": {
    "table": "block",
    "id": "be3268c5-993a-46a1-9b07-d2534910c41d",
    "spaceId": "90498861-ad69-4209-93af-29c4b6309733"
  }
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/enex_uploader.py", line 28, in upload_note
    upload_block(new_page, block)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/enex_uploader_block.py", line 16, in upload_block
    _upload_file(new_block, block.resource)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/enex_uploader_block.py", line 41, in _upload_file
    upload_data = new_block._client.post(  # noqa: WPS437
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/notion/client.py", line 290, in _post
    raise HTTPError(
requests.exceptions.HTTPError: Uploading .jar files is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/enex2notion", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 47, in main
    cli(sys.argv[1:])
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 32, in cli
    _process_input(enex_uploader, args.enex_input)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 42, in _process_input
    enex_uploader.upload_notebook(path)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 56, in upload_notebook
    self.upload_note(note, note_idx)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 79, in upload_note
    _upload_note(self.notebook_root, note, note_blocks)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 103, in _upload_note
    upload_note(notebook_root, note, note_blocks)
  File "/opt/homebrew/Cellar/enex2notion/0.2.18/libexec/lib/python3.10/site-packages/enex2notion/enex_uploader.py", line 35, in upload_note
    raise NoteUploadFailException
enex2notion.utils_exceptions.NoteUploadFailException
```

**Comment by vzhd1701** [comment]
Done. Homebrew version should be updated in a few hours.

**Comment by bxb100** [comment]
Nice work, Thanks
