### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by ma3252788** [vzhd1701/enex2notion#51]
### enex2notion version

enex2notion 0.2.19

### What OS are you using?

MacOS

### OS Version / Linux distribution

12.5

### Bug description

When I use `python -m enex2notion --token 6d5e5b2e50122axxxxxxxx output_dir/`

I got:

```
Traceback (most recent call last):
  File "/Users/mcj/anaconda3/envs/py3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mcj/anaconda3/envs/py3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mcj/.local/lib/python3.7/site-packages/enex2notion/__main__.py", line 4, in <module>
    main()
  File "/Users/mcj/.local/lib/python3.7/site-packages/enex2notion/cli.py", line 47, in main
    cli(sys.argv[1:])
  File "/Users/mcj/.local/lib/python3.7/site-packages/enex2notion/cli.py", line 26, in cli
    root = get_root(args.token, args.root_page)
  File "/Users/mcj/.local/lib/python3.7/site-packages/enex2notion/cli_notion.py", line 21, in get_root
    client = get_notion_client(token)
  File "/Users/mcj/.local/lib/python3.7/site-packages/enex2notion/cli_notion.py", line 31, in get_notion_client
    return NotionClient(token_v2=token)
  File "/Users/mcj/.local/lib/python3.7/site-packages/notion/client.py", line 88, in __init__
    self.session = create_session(client_specified_retry)
  File "/Users/mcj/.local/lib/python3.7/site-packages/notion/client.py", line 53, in create_session
    "POST",
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**Comment by vzhd1701** [comment]
You have a dependency version conflict. You should uninstall `enex2notion` and reinstall it using Homebrew or install it in a virtual environment.

**Comment by ma3252788** [comment]
Yes, when I change to homebrew, it works!

Thank you !
