### ISSUE TITLE
[Bug]: requests.exceptions.HTTPError: Uploading .apk files is not allowed

### ISSUE THREAD

**Issue by ma3252788** [vzhd1701/enex2notion#52]
### enex2notion version

enex2notion 0.2.19

### What OS are you using?

Linux

### OS Version / Linux distribution

16.04

### Bug description

Because apk file, I got this :

```
WARNING: Failed to upload note '安卓版QQ微信百变语音变声器，修复卡密激' to Notion! Retrying...
 89%|███████████████████████████████████▊    | 34/38 [00:14<00:02,  2.00block/s]ERROR: Got 400 error attempting to POST to getUploadFileUrl, with data: {
  "bucket": "secure",
  "name": "\u8587\u8fb0\u8bed\u97f3\u52a9\u624bV1.5.apk",
  "contentType": "application/octet-stream",
  "record": {
    "table": "block",
    "id": "04dc5344-876c-4d28-b318-ddae9ad196a0",
    "spaceId": "47712955-f40b-4bdf-82df-50bdd22aee8c"
  }
}
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/enex2notion/enex_uploader.py", line 28, in upload_note
    upload_block(new_page, block)
  File "/root/.local/lib/python3.8/site-packages/enex2notion/enex_uploader_block.py", line 16, in upload_block
    _upload_file(new_block, block.resource)
  File "/root/.local/lib/python3.8/site-packages/enex2notion/enex_uploader_block.py", line 41, in _upload_file
    upload_data = new_block._client.post(  # noqa: WPS437
  File "/root/.local/lib/python3.8/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/root/.local/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/root/.local/lib/python3.8/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
  File "/root/.local/lib/python3.8/site-packages/notion/client.py", line 290, in _post
    raise HTTPError(
requests.exceptions.HTTPError: Uploading .apk files is not allowed
```

**Comment by vzhd1701** [comment]
Fixed. Now files with banned extensions will be uploaded as `.bin` files.

**Comment by ma3252788** [comment]
> Fixed. Now files with banned extensions will be uploaded as `.bin` files.

Thank you, Bug I found this new problem:

```WARNING: Failed to upload note '【mcj】Zotero使用说明' to Notion! Retrying...
  9%|███▊                                     | 7/75 [00:04<00:44,  1.54block/s]ERROR: Got 400 error attempting to POST to getUploadFileUrl, with data: {
  "bucket": "secure",
  "name": "zotfile-5.0.16-fx.xpi",
  "contentType": "application/octet-stream",
  "record": {
    "table": "block",
    "id": "0291be12-9cc8-4a8a-9faa-68bd62e2bcf6",
    "spaceId": "47712955-f40b-4bdf-82df-50bdd22aee8c"
  }
}
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3/lib/python3.8/site-packages/enex2notion/enex_uploader.py", line 28, in upload_note
    upload_block(new_page, block)
  File "/root/anaconda3/envs/py3/lib/python3.8/site-packages/enex2notion/enex_uploader_block.py", line 16, in upload_block
    _upload_file(new_block, block.resource)
  File "/root/anaconda3/envs/py3/lib/python3.8/site-packages/enex2notion/enex_uploader_block.py", line 41, in _upload_file
    upload_data = new_block._client.post(  # noqa: WPS437
  File "/root/.local/lib/python3.8/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/root/.local/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/root/.local/lib/python3.8/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
  File "/root/.local/lib/python3.8/site-packages/notion/client.py", line 290, in _post
    raise HTTPError(
requests.exceptions.HTTPError: Uploading .xpi files is not allowed

During handling of the above exception, another exception occurred:
```

**Comment by vzhd1701** [comment]
Sorry that this bug keeps returning. I don't have the full list of all banned extensions at Notion, so I have to fix it one at a time. `xpi` is now in the banned list. Check out the new version.
