### ISSUE TITLE
In the middle of a note import i get NoneType object has no attribute 'get' and everything crashes

### ISSUE THREAD

**Issue by anogues** [vzhd1701/enex2notion#65]
Hi.

After two notebooks imported successfully and some notes of the current one i get one crashing which stops everything:

DEBUG: Creating new page for note '¿Están exentos los rendimientos del trabajo obtenidos en el extranjero? - Billage CRM'
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\enex2notion.exe\__main__.py", line 7, in <module>
  File "C:\Python\lib\site-packages\enex2notion\cli.py", line 47, in main
    cli(sys.argv[1:])
  File "C:\Python\lib\site-packages\enex2notion\cli.py", line 32, in cli
    _process_input(enex_uploader, args.enex_input)
  File "C:\Python\lib\site-packages\enex2notion\cli.py", line 40, in _process_input
    enex_uploader.upload_notebook(enex_file)
  File "C:\Python\lib\site-packages\enex2notion\cli_upload.py", line 55, in upload_notebook
    for note_idx, note in enumerate(iter_notes(enex_file), 1):
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 27, in iter_notes
    yield from (_process_note(e) for e in iter_xml_elements_as_dict(enex_file, "note"))
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 27, in <genexpr>
    yield from (_process_note(e) for e in iter_xml_elements_as_dict(enex_file, "note"))
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 53, in _process_note
    resources=_parse_resources(note_raw),
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 63, in _parse_resources
    return [_convert_resource(r) for r in note_resources]
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 63, in <listcomp>
    return [_convert_resource(r) for r in note_resources]
  File "C:\Python\lib\site-packages\enex2notion\enex_parser.py", line 105, in _convert_resource
    if resource_raw.get("data", {}).get("#text"):
AttributeError: 'NoneType' object has no attribute 'get'

Regards,
Albert

**Comment by vzhd1701** [comment]
Could you please share the note that is causing this crash?

**Comment by ConnorCrwf** [comment]
@vzhd1701 
I'm not sure if this is the same error, but here's my error. I changed all my IDs to redacted.

INFO: Uploading note 1 out of 19 'Operating Manual (Record and Play Bags)'
ERROR: Got 400 error attempting to POST to submitTransaction, with data: {
  "operations": [
    {
      "id": "redacted",
      "path": [],
      "args": {
        "id": "redcated",
        "version": 1,
        "alive": true,
        "created_by_id": "redacted",
        "created_by_table": "notion_user",
        "created_time": 1670455636141,
        "parent_id": "redacted",
        "parent_table": "collection",
        "type": "page"
      },
      "command": "set",
      "table": "block"
    },
    {
      "args": {
        "last_edited_by_id": "redacted",
        "last_edited_by_table": "notion_user",
        "last_edited_time": 1670455636141
      },
      "command": "update",
      "id": "redacted",
      "path": [],
      "table": "block"
    },
    {
      "args": {
        "last_edited_by_id": "redacted",
        "last_edited_by_table": "notion_user",
        "last_edited_time": 1670455636141
      },
      "command": "update",
      "id": "35518e5d-6554-4083-901d-16d5d6072aef",
      "path": [],
      "table": "block"
    }
  ]
}
Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 32, in cli
  File "enex2notion\cli.py", line 42, in _process_input
  File "enex2notion\cli_upload.py", line 56, in upload_notebook
  File "enex2notion\cli_upload.py", line 79, in upload_note
  File "enex2notion\cli_upload.py", line 103, in _upload_note
  File "enex2notion\enex_uploader.py", line 20, in upload_note
  File "enex2notion\enex_uploader.py", line 59, in _make_page
  File "notion\collection.py", line 202, in add_row
  File "notion\collection.py", line 213, in add_row_block
  File "notion\client.py", line 427, in create_record
  File "notion\client.py", line 468, in __exit__
  File "notion\client.py", line 323, in submit_transaction
  File "ratelimit\decorators.py", line 113, in wrapper
  File "ratelimit\decorators.py", line 80, in wrapper
  File "notion\client.py", line 275, in post
  File "notion\client.py", line 290, in _post
requests.exceptions.HTTPError: Unsaved transactions: SpaceShardRecordPointer have no space id
[29284] Failed to execute script '__main__' due to unhandled exception!
