### ISSUE TITLE
[Bug]: Error when connection timeout/failure occurs

### ISSUE THREAD

**Issue by RobATX** [vzhd1701/enex2notion#92]
### enex2notion version

v0.2.26

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11 22621.1778

### Bug description

This is more of an FYI and question about handling of connection issues/timeouts. I'm assuming based on these errors that Notion's API has stopped responding. This happens mostly on large batches with 100+ notes. Let me know if you would like me to run with verbose set. Thank you so much for the work you've put in on this utility. It is a lifesaver. 🖖

INFO: Uploading note 32 out of 461 'Android Forums at AndroidCentral.com'
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 419, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 419, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 32, in cli
  File "enex2notion\cli.py", line 42, in _process_input
  File "enex2notion\cli_upload.py", line 56, in upload_notebook
  File "enex2notion\cli_upload.py", line 79, in upload_note
  File "enex2notion\cli_upload.py", line 103, in _upload_note
  File "enex2notion\enex_uploader.py", line 28, in upload_note
  File "enex2notion\enex_uploader_block.py", line 16, in upload_block
  File "enex2notion\enex_uploader_block.py", line 45, in _upload_file
  File "requests\api.py", line 130, in put
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
[43816] Failed to execute script '__main__' due to unhandled exception!

**Comment by vzhd1701** [comment]
I've added --retry option so you could increase retries in case of repeating network errors.
