### ISSUE TITLE
[Bug]: Parse error

### ISSUE THREAD

**Issue by saijunhu** [vzhd1701/enex2notion#97]
### enex2notion version

0.2.26

### What OS are you using?

Windows

### OS Version / Linux distribution

win11

### Bug description

![image](https://github.com/vzhd1701/enex2notion/assets/15167786/2db66939-e596-497f-8377-d3e10d5fbd9a)
这个是啥错误，一运行就报这个，python3.8

**Comment by ConnorCrwf** [comment]
Same issue:

```
INFO: Creating 'Evernote ENEX Import' page...
INFO: Processing notebook 'notebook'...
Traceback (most recent call last):
  File "enex2notion\__main__.py", line 4, in <module>
  File "enex2notion\cli.py", line 47, in main
  File "enex2notion\cli.py", line 32, in cli
  File "enex2notion\cli.py", line 42, in _process_input
  File "enex2notion\cli_upload.py", line 53, in upload_notebook
  File "enex2notion\enex_parser.py", line 23, in count_notes
  File "enex2notion\enex_parser_xml.py", line 23, in iter_process_xml_elements
  File "xml\etree\ElementTree.py", line 1227, in iterator
  File "xml\etree\ElementTree.py", line 1302, in read_events
  File "xml\etree\ElementTree.py", line 1274, in feed
xml.etree.ElementTree.ParseError: undefined entity &nbsp;: line 21402, column 202
[29924] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by vzhd1701** [comment]
This should be fixed now. Please check out the new version.
